name: Create Release Tag
on:
  workflow_dispatch:
    inputs:
      TagVersion:
        description: 'Tag version'
        required: true
        default: 'v1.0.0'
        type: string
      ReleaseName:
        description: 'Release name'
        required: true
        default: 'v1.0.0'
        type: string
      PreRelease:
        description: 'If it is a pre-release'
        required: true
        default: true
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Zip folder
        run: |
          cd src
          zip -r promptflow-tools.zip promptflow-tools

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ inputs.TagVersion }}
          release_name: ${{ inputs.ReleaseName }}
          body: Description of the release
          draft: false
          prerelease: ${{ inputs.PreRelease }}

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./src/promptflow-tools.zip
          asset_name: promptflow-tools.zip
          asset_content_type: application/zip
